name: Stock Data Stream

on:
  push:
    branches:
      - main

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install scratchapi alpaca-trade-api
      - name: Run stock streaming script
        run: |
          python main.py
